# Generated by Django 5.1.5 on 2025-05-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('accessory', 'Accessory'), ('outerwear', 'Outerwear')], max_length=10)),
                ('color', models.TextField()),
                ('image', models.ImageField(upload_to='clothing_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('event_date', models.DateField()),
                ('location', models.TextField()),
                ('outfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.outfit')),
            ],
        ),
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.clothingitem')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_items', to='project.outfit')),
            ],
        ),
    ]
