# Generated by Django 5.1.5 on 2025-05-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='type',
            field=models.CharField(choices=[('top', 'Top'), ('dresses', 'Dresses'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('accessory', 'Accessory'), ('outerwear', 'Outerwear')], max_length=10),
        ),
    ]
