# Generated by Django 5.1.6 on 2025-02-21 19:56
"""
Author: Derinell Rojas
Email: droja@bu.edu
Date: 2025-02-27
Description: Migration file that create Profile model with fields including 
first name, last name, city, email, and profile id
"""


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('city', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('image', models.TextField(blank=True)),
            ],
        ),
    ]
