# Generated by Django 5.1.6 on 2025-02-27 14:57

import django.db.models.deletion
from django.db import migrations, models
"""
Author: Derinell Rojas
Email: droja@bu.edu
Date: 2025-02-27
Description: Migration file that create Status model with fields including 
profile reference, message, timestamp and status id
"""

class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_fb.profile')),
            ],
        ),
    ]
