# Generated by Django 5.1.5 on 2025-03-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0004_image_statusimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='statusimage',
            name='status_message',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_file',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='StatusImage',
        ),
    ]
